#!/usr/bin/env python3

import ast
import cvisitors
import hvisitors
import argparse
import datetime
import ooctypes

version = '0.1'


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Transforms python-like code into OOC code', add_help=False)
    parser.add_argument('--help', action='help', help='show this help message and exit')
    parser.add_argument('--input', '-i', required=True, help='Input file')
    parser.add_argument('--source', '-s', action='store_true', help='Write source code')
    parser.add_argument('--headers', '-h', action='store_true', help='Write headers')
    parser.add_argument('--debug', '-d', action='store_true', required=False, help='Use debug output')
    parser.add_argument('--verbose', '-v', action='store_true', required=False, help='Use verbose output')
    parser.add_argument('--pretend', '-p', action='store_true', required=False, help='Only pretend to write to files')
    parser.add_argument('--include', '-I', nargs='+', required=False, help='Include dirs while looking for header files')

    args = parser.parse_args()
    with open(args.input) as f:
        source = f.read()

    out_source = '%sc' % args.input
    out_headers = '%sh' % args.input

    file_header = '/* Generated by py2occ v. %s from %s on %s\n\n' % (version, args.input, str(datetime.datetime.now())[:19])
    file_header += 'Input file:\n%s\n*/\n\n' % source

    hcode = ''
    ccode = '#include "%s"\n' % out_headers

    if args.include:
        known_types = ooctypes.process_dirs(args.include, debug=args.debug)

    root = ast.parse(source)
    if args.debug:
        print(ast.dump(root))
    for node in root.body:
        if args.debug:
            print(ast.dump(node))
        if args.source:
            visitor = cvisitors.RootVisitor({}, None)
            visitor.visit(node)
            ccode += visitor.code
        if args.headers:
            visitor = hvisitors.RootVisitor()
            visitor.visit(node)
            hcode += visitor.code

    if not args.pretend and args.source:
        with open(out_source, 'w') as f:
            f.write(file_header)
            f.write(ccode)

    if not args.pretend and args.headers:
        with open(out_headers, 'w') as f:
            f.write(file_header)
            f.write(hcode)

    if args.verbose and args.headers:
        print('#' * 50)
        print('#   ', out_headers)
        print('#' * 50)
        print(hcode)
    if args.verbose and args.source:
        print('#' * 50)
        print('#   ', out_source)
        print('#' * 50)
        print(ccode)

